### ISSUE TITLE
Request for creation of a forum - raw materials theme - GeoERA /  Harmonization & technical issues

### ISSUE THREAD

**Issue by ManuelFilipeSantos65** [GeoEra-GIP/Project-Support-WP8#30]
Dear team,

Hope to find you well.

Within the scope of the Lisbon FRAME workshop of the past 17-18th September, it has been decided that it would be important if the GeoERA projects, namely the raw materials theme, could have a place where to promote good practices, tackle implementation / technical issues related to data set harmonization and harvesting processes or simply for sharing experiences.

Can you please assist with this request by creating such a forum and please confirm, if necessary, with the Mintell4EU/Minerals4EU/GIP-P teams at GEUS  ?

Kind regards and thank you in advance,
Filipe Santos.
Waymotion / LNEG
Tm: +351963981844

**Comment by KoalaGeo** [comment]
Hi Filipe, 

I've created a repository (https://github.com/GeoEra-GIP/Minerals4EU), this would be the place to write and document any best practices that you might like to share wit the group. 

I've also created a team (https://github.com/orgs/GeoEra-GIP/teams/minerals4eu) which gives  discussion board functionality. 

Is this what you were after?

**Comment by nmtoken** [comment]
Really not sure if Minerals4EU is best super-category to capture all this info, better if it were Raw Materials.  That would cover the FRAME and Mintell4EU current activities, plus the older minerals projects like [Minerals4EU](http://www.minerals4eu.eu/), [EuRare](http://www.eurare.eu/), [ProSUM](http://www.prosumproject.eu/) and possibly [MICA](http://www.mica-project.eu/) and [ORAMA](https://orama-h2020.eu/)

**Comment by LisbethFlindtJorgensen** [comment]
I think that would be a too wide, or at least then requiring sub-categories. 
What was requested here was a forum for data providers uploading data to Minerals4EU to share experiences on uploads and for the GeoZS experts to reply/communicate. What we see at the project meetings is that these data providers are not the same persons as those working in the projects.

**Comment by nmtoken** [comment]
No need for physical subcategories, but semantically it seems incorrect to have Minerals4EU as the parent.

The request above doesn't specifically mention Minerals4EU, rather is more generic 

> to promote good practices, tackle implementation / technical issues related to data set harmonization and harvesting processes or simply for sharing experiences.

Rather than:

> What was requested here was a forum for data providers uploading data to Minerals4EU to share experiences on uploads and for the GeoZS experts to reply/communicate.

Just on terminology though this is already incorrect.  For Eurare/Minerals4EU/ProSum, data providers configure WFS services (or a single service) that that can be harvested by GeoEra projects and other platforms;  they don't upload anything.   The requirement on the data providers is provision of services that use ERML.  If they use documentation (and out of the box solution) that was created for the MineralsEU project, then those services will be following good practices, be standards compliant and use codelists.

**Comment by KoalaGeo** [comment]
Think we've now finalised a solution, so I'll close the issue.
